### ISSUE TITLE
Order History Page

### ISSUE THREAD

**Issue by slytherin20** [slytherin20/Zungry#14]
It should show all the orders placed.
Each order card should have following information:

- [x]  Restaurant Name
- [x] Order status
- [x] Restaurant locality
- [x] Total Amount paid
- [x] Order items
- [x] Date and time
- [x] #20 (Button on Orders List page)
- [x] #21 (Button on Orders List page)
- [x] #22 (Button on Orders List page)

**Comment by slytherin20** [comment]
Orders list component completed.
